export enum AncestryId {
  HUMAN = 'ancestry:human',
  DWARF = 'ancestry:dwarf',
  ELF = 'ancestry:elf',
  GNOME = 'ancestry:gnome',
  HALFLING = 'ancestry:halfling',
  OGRE = 'ancestry:ogre',
}

export enum SkillId {
  ALCHEMY = 'skill:alchemy',
  ATHLETICS = 'skill:athletics',
  AWARENESS = 'skill:awareness',
  BARGAIN = 'skill:bargain',
  CHARM = 'skill:charm',
  COORDINATION = 'skill:coordination',
  COUNTERFEIT = 'skill:counterfeit',
  DISGUISE = 'skill:disguise',
  DRIVE = 'skill:drive',
  EAVESDROP = 'skill:eavesdrop',
  EDUCATION = 'skill:education',
  FOLKLORE = 'skill:folklore',
  GAMBLE = 'skill:gamble',
  GUILE = 'skill:guile',
  HANDLE_ANIMAL = 'skill:handle_animal',
  HEAL = 'skill:heal',
  INCANTATION = 'skill:incantation',
  INTERROGATION = 'skill:interrogation',
  INTIMIDATE = 'skill:intimidate',
  LEADERSHIP = 'skill:leadership',
  MARTIAL_MELEE = 'skill:martial_melee',
  MARTIAL_RANGED = 'skill:martial_ranged',
  NAVIGATION = 'skill:navigation',
  PILOT = 'skill:pilot',
  RESOLVE = 'skill:resolve',
  RIDE = 'skill:ride',
  RUMOR = 'skill:rumor',
  SCRUTINIZE = 'skill:scrutinize',
  SIMPLE_MELEE = 'skill:simple_melee',
  SIMPLE_RANGED = 'skill:simple_ranged',
  SKULDUGGERY = 'skill:skulduggery',
  STEALTH = 'skill:stealth',
  SURVIVAL = 'skill:survival',
  TOUGHNESS = 'skill:toughness',
  TRADECRAFT = 'skill:tradecraft',
  WARFARE = 'skill:warfare',
}
