export enum AlignmentId {
  ADAPTATION = 'alignment:adaptation',
  MAYHEM = 'alignment:mayhem',
  AMBITION = 'alignment:ambition',
  TYRANNY = 'alignment:tyranny',
  CANDOR = 'alignment:candor',
  CRUELTY = 'alignment:cruelty',
  CHARITY = 'alignment:charity',
  PITY = 'alignment:pity',
  COMPASSION = 'alignment:compassion',
  MELANCHOLY = 'alignment:melancholy',
  CUNNING = 'alignment:cunning',
  DECEIT = 'alignment:deceit',
  DIGNITY = 'alignment:dignity',
  VEHEMENCE = 'alignment:vehemence',
  DIPLOMACY = 'alignment:diplomacy',
  HYPOCRISY = 'alignment:hypocrisy',
  DUTY = 'alignment:duty',
  FATALISM = 'alignment:fatalism',
  ENLIGHTENMENT = 'alignment:enlightenment',
  DETACHMENT = 'alignment:detachment',
  FEROCITY = 'alignment:ferocity',
  HATRED = 'alignment:hatred',
  GENTILITY = 'alignment:gentility',
  COWARDICE = 'alignment:cowardice',
  GRAVITAS = 'alignment:gravitas',
  VANITY = 'alignment:vanity',
  HEROISM = 'alignment:heroism',
  MARTYRDOM = 'alignment:martyrdom',
  HUMILITY = 'alignment:humility',
  INCOMPETENCE = 'alignment:incompetence',
  IMPIETY = 'alignment:impiety',
  HERESY = 'alignment:heresy',
  INDEPENDENCE = 'alignment:independence',
  REBELLION = 'alignment:rebellion',
  MYSTERY = 'alignment:mystery',
  EXCLUSION = 'alignment:exclusion',
  PRIDE = 'alignment:pride',
  ARROGANCE = 'alignment:arrogance',
  ROMANTICISM = 'alignment:romanticism',
  LECHERY = 'alignment:lechery',
  SKEPTICISM = 'alignment:skepticism',
  CYNICISM = 'alignment:cynicism',
  SOPHISTICATION = 'alignment:sophistication',
  INDULGENCE = 'alignment:indulgence',
  WISDOM = 'alignment:wisdom',
  RANCOR = 'alignment:rancor',
  WIT = 'alignment:wit',
  SCORN = 'alignment:scorn',
  ZEAL = 'alignment:zeal',
  FANATICISM = 'alignment:fanaticism'
}

export enum AncestryId {
  HUMAN = 'ancestry:human',
  DWARF = 'ancestry:dwarf',
  ELF = 'ancestry:elf',
  GNOME = 'ancestry:gnome',
  HALFLING = 'ancestry:halfling',
  OGRE = 'ancestry:ogre',
}

export enum ArchetypeId {
  ACADEMIC = 'archetype:academic',
  COMMONER = 'archetype:commoner',
  KNAVE = 'archetype:knave',
  RANGER = 'archetype:ranger',
  SOCIALITE = 'archetype:socialite',
  WARRIOR = 'archetype:warrior'
}

export enum AttributeId {
  COMBAT = 'attribute:combat',
  BRAWN = 'attribute:brawn',
  AGILITY = 'attribute:agility',
  PERCEPTION = 'attribute:perception',
  INTELLIGENCE = 'attribute:intelligence',
  WILLPOWER = 'attribute:willpower',
  FELLOWSHIP = 'attribute:fellowship'
}

export enum DrawbackId {
  BAD_TICKER = 'drawback:bad_ticker',
  BLACK_CATARACT = 'drawback:black_cataract',
  BLEEDER = 'drawback:bleeder',
  BRANDED = 'drawback:branded',
  CHOLERIC_TEMPERAMENT = 'drawback:choleric_temperament',
  CROP_EAR = 'drawback:crop_ear',
  CURSED = 'drawback:cursed',
  DEAL_WITH_THE_DEVIL = 'drawback:deal_with_the_devil',
  DEBTRIDDEN = 'drawback:debtridden',
  DUNDERHEAD = 'drawback:dunderhead',
  EUNUCH = 'drawback:eunuch',
  LILYLIVERED = 'drawback:lilylivered',
  MELANCHOLIC_TEMPERAMENT = 'drawback:melancholic_temperament',
  NEER_DO_WELL = 'drawback:neer_do_well',
  NEMESIS = 'drawback:nemesis',
  PAINKILLER = 'drawback:painkiller',
  PERSECUTION_COMPLEX = 'drawback:persecution_complex',
  PHLEGMATIC_TEMPERAMENT = 'drawback:phlegmatic_temperament',
  SANGUINE_TEMPERAMENT = 'drawback:sanguine_temperament',
  SOUR_STOMACH = 'drawback:sour_stomach',
  SPLIT_FACE = 'drawback:split_face',
  VETERANS_BOOT = 'drawback:veterans_boot',
  VETERANS_EYE = 'drawback:veterans_eye',
  VETERANS_HAND = 'drawback:veterans_hand',
  VETERANS_LEG = 'drawback:veterans_leg',
  WEAK_LUNGS = 'drawback:weak_lungs'
}

export enum ProfessionId {
  ADHERENT = 'profession:adherent',
  ANARCHIST = 'profession:anarchist',
  ANCHORITE = 'profession:anchorite',
  ANIMAL_TAMER = 'profession:animal_tamer',
  ANTIQUARIAN = 'profession:antiquarian',
  APOTHECARY = 'profession:apothecary',
  ARTISAN = 'profession:artisan',
  ASTROLOGER = 'profession:astrologer',
  BAILIFF = 'profession:bailiff',
  BARBER_SURGEON = 'profession:barber_surgeon',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
  // ADHERENT = 'profession:adherent',
}

export enum SkillId {
  ALCHEMY = 'skill:alchemy',
  ATHLETICS = 'skill:athletics',
  AWARENESS = 'skill:awareness',
  BARGAIN = 'skill:bargain',
  CHARM = 'skill:charm',
  COORDINATION = 'skill:coordination',
  COUNTERFEIT = 'skill:counterfeit',
  DISGUISE = 'skill:disguise',
  DRIVE = 'skill:drive',
  EAVESDROP = 'skill:eavesdrop',
  EDUCATION = 'skill:education',
  FOLKLORE = 'skill:folklore',
  GAMBLE = 'skill:gamble',
  GUILE = 'skill:guile',
  HANDLE_ANIMAL = 'skill:handle_animal',
  HEAL = 'skill:heal',
  INCANTATION = 'skill:incantation',
  INTERROGATION = 'skill:interrogation',
  INTIMIDATE = 'skill:intimidate',
  LEADERSHIP = 'skill:leadership',
  MARTIAL_MELEE = 'skill:martial_melee',
  MARTIAL_RANGED = 'skill:martial_ranged',
  NAVIGATION = 'skill:navigation',
  PILOT = 'skill:pilot',
  RESOLVE = 'skill:resolve',
  RIDE = 'skill:ride',
  RUMOR = 'skill:rumor',
  SCRUTINIZE = 'skill:scrutinize',
  SIMPLE_MELEE = 'skill:simple_melee',
  SIMPLE_RANGED = 'skill:simple_ranged',
  SKULDUGGERY = 'skill:skulduggery',
  STEALTH = 'skill:stealth',
  SURVIVAL = 'skill:survival',
  TOUGHNESS = 'skill:toughness',
  TRADECRAFT = 'skill:tradecraft',
  WARFARE = 'skill:warfare'
}

export enum TalentId {}

export enum TraitId {
  BLESSING_IN_DISGUISE = 'trait:blessing_in_disguise',
  DANGER_SENSE = 'trait:danger_sense',
  DAUNTLESS = 'trait:dauntless',
  ESOTERIC_MEMORY = 'trait:esoteric_memory',
  FORTUNES_WHEEL = 'trait:fortunes_wheel',
  GRIM_RESOLVE = 'trait:grim_resolve',
  MANIFEST_DESTINY = 'trait:manifest_destiny',
  MIXED_BLOODLINE = 'trait:mixed_bloodline',
  MOUNTAIN_AMONGST_MEN = 'trait:mountain_amongst_men',
  NATURAL_SELECTION = 'trait:natural_selection',
  NOBLE_SAVAGE = 'trait:noble_savage',
  SEVENTH_SENSE = 'trait:seventh_sense',
  CAVESIGHT = 'trait: cavesight',
  CHILDREN_OF_THE_EARTH = 'trait:children_of_the_earth',
  CONSUME_ALCOHOL = 'trait:consume_alcohol',
  DWARVEN_WARFARE = 'trait:dwarven_warfare',
  GRUDGEBEARER = 'trait:grudgebearer',
  IRONCLAD = 'trait:ironclad',
  OATHKEEPER = 'trait:oathkeeper',
  PHYSICAL_PROWESS = 'trait:physical_prowess',
  RUNEMARKED_GLORY = 'trait:runemarked_glory',
  STENTORIAN_VOICE = 'trait:stentorian_voice',
  STONEHEADED = 'trait:stoneheaded',
  STRENGTH_OF_THE_MOUNTAIN = 'trait:strength_of_the_mountain',
  BEWITCHING = 'trait:bewitching',
  BEYOND_THE_VEIL = 'trait:beyond_the_veil',
  DEADLY_AIM = 'trait:deadly_aim',
  ENDURING_MORTALITY = 'trait:enduring_mortality',
  FEY_TREACHERY = 'trait:fey_treachery',
  FIRSTBORN = 'trait:firstborn',
  KINDRED_WARBAND = 'trait:kindred_warband',
  LAMENT_OF_THE_AGES = 'trait:lament_of_the_ages',
  MEDITATIVE_HEALING = 'trait:meditative_healing',
  NATURES_OWN = 'trait:natures_own',
  NIGHTEYES = 'trait:nighteyes',
  WARRIORS_TATTOO = 'trait:warriors_tattoo',
  CLOCKWORKS_OF_WAR = 'trait:clockworks_of_war',
  CRAG_FIGHTING = 'trait:crag_fighting',
  DENIZEN_OF_STONE = 'trait:denizen_of_stone',
  DUNGEONS_DEEP = 'trait:dungeons_deep',
  ESCAPE_ARTIST = 'trait:escape_artist',
  GOLDBERGIAN = 'trait:goldbergian',
  HOCUS_POCUS = 'trait:hocus_pocus',
  METROGNOME = 'trait:metrognome',
  THIEVING_STUNTIES = 'trait:thieving_stunties',
  TUNNEL_VISION = 'trait:tunnel_vision',
  UNDERFOOT = 'trait:underfoot',
  WRETCHED_PRANKSTER = 'trait:wretched_prankster',
  BEGUILER = 'trait:beguiler',
  CATLIKE_REFLEXES = 'trait:catlike_reflexes',
  CRAVEN = 'trait:craven',
  FARSIGHT = 'trait:farsight',
  FETTERED_CHAOS = 'trait:fettered_chaos',
  FIELDWARDEN = 'trait:fieldwarden',
  FLEETFOOTED = 'trait:fleetfooted',
  HIJINKS = 'trait:hijinks',
  KLEPTOMANIA = 'trait:kleptomania',
  LOW_BLOW = 'trait:low_blow',
  MEMENTO = 'trait:memento',
  PINTSIZED = 'trait:pintsized',
  BROADBELLIED = 'trait:broadbellied',
  CAST_IRON_STOMACH = 'trait:cast_iron_stomach',
  CRUISIN_FOR_A_BRUISIN = 'trait:cruisin_for_a_bruisin',
  FRIGHTENING_BELLOW = 'trait:frightening_bellow',
  GUTPLATE = 'trait:gutplate',
  HUNGER_PANGS = 'trait:hunger_pangs',
  MIGHTY_THEWS = 'trait:mighty_thews',
  ODD_COUPLE = 'trait:odd_couple',
  ROTGUT_SPRAY = 'trait:rotgut_spray',
  SLAMDANCE = 'trait:slamdance',
  THICK_LINING = 'trait:thick_lining',
  WENDIGO = 'trait:wendigo'
}

export enum UpbringingId {
  CULTURED = 'upbringing:cultured',
  FORGOTTEN = 'upbringing:forgotten',
  INDUSTRIOUS = 'upbringing:industrious',
  MILITANT = 'upbringing:militant',
  OPPORTUNISTIC = 'upbringing:opportunistic',
  REVERENT = 'upbringing:reverent',
  SCHOLASTIC = 'upbringing:scholastic'
}
