export enum ATTRIBUTE_ID {
  BODY = 'attribute:body',
  AGILITY = 'attribute:agility',
  REACTION = 'attribute:reaction',
  STRENGTH = 'attribute:strength',
  WILLPOWER = 'attribute:willpower',
  LOGIC = 'attribute:logic',
  INTUITION = 'attribute:intuition',
  CHARISMA = 'attribute:charisma',
  EDGE = 'attribute:edge',
  ESSENCE = 'attribute:essence',
  MAGIC = 'attribute:magic',
  RESONANCE = 'attribute:resonance'
}

export enum ATTRIBUTE_TYPE_ID {
  PHYSICAL = 'physical',
  MENTAL = 'mental',
  SPECIAL = 'special'
}

export enum AWAKENING_ID {
  MUNDANE = 'awakening:mundane',
  ADEPT = 'awakening:adept',
  ASPECTED_MAGICIAN = 'awakening:aspected_magician',
  MAGICIAN = 'awakening:magician',
  MYSTIC_ADEPT = 'awakening:mystic_adept',
  TECHNOMANCER = 'awakening:technomancer'
}

export enum BOOK_ID {
  CORE_RULEBOOK = '5e:core_rulebook'
}

export enum METATYPE_ID {
  HUMAN = 'metatype:human',
  DWARF = 'metatype:dwarf',
  ELF = 'metatype:elf',
  ORK = 'metatype:ork',
  TROLL = 'metatype:troll'
}

export enum QUALITY_ID {
  AMBIDEXTROUS = 'quality:ambidextrous',
  ANALYTICAL_MIND = 'quality:analytical_mind',
  APTITUDE = 'quality:aptitude',
  ASTRAL_CHAMELEON = 'quality:astral_chameleon',
  BILINGUAL = 'quality:bilingual',
  BLANDNESS = 'quality:blandness',
  CATLIKE = 'quality:catlike',
  CODESLINGER = 'quality:codeslinger',
  DOUBLE_JOINTED = 'quality:double_jointed',
  EXCEPTIONAL_ATTRIBUTE = 'quality:exceptional_attribute',
  FIRST_IMPRESSION = 'quality:first_impression',
  FOCUSED_CONCENTRATION = 'quality:focused_concentration',
  GEARHEAD = 'quality:gearhead',
  GUTS = 'quality:guts',
  HIGH_PAIN_TOLERANCE = 'quality:high_pain_tolerance',
  HOME_GROUND = 'quality:home_ground',
  HUMAN_LOOKING = 'quality:human_looking',
  INDOMITABLE = 'quality:indomitable',
  JURYRIGGER = 'quality:juryrigger',
  LUCKY = 'quality:lucky',
  MAGIC_RESISTANCE = 'quality:magic_resistance',
  MENTOR_SPIRIT = 'quality:mentor_spirit',
  NATURAL_ATHLETE = 'quality:natural_athlete',
  NATURAL_HARDENING = 'quality:natural_hardening',
  NATURAL_IMMUNITY = 'quality:natural_immunity',
  PHOTOGRAPHIC_MEMORY = 'quality:photographic_memory',
  QUICK_HEALER = 'quality:quick_healer',
  RESISTANCE_TO_PATHOGENS = 'quality:resistance_to_pathogens',
  SPIRIT_AFFINITY = 'quality:spirit_affinity',
  TOUGHNESS = 'quality:toughness',
  WILL_TO_LIVE = 'quality:will_to_live',
  // ****
  ADDICTION = 'quality:addiction',
  ALLERGY = 'quality:allergy',
  ASTRAL_BEACON = 'quality:astral_beacon',
  BAD_LUCK = 'quality:bad_luck',
  BAD_REP = 'quality:bad_rep',
  CODE_OF_HONOR = 'quality:code_of_honor',
  CODEBLOCK = 'quality:codeblock',
  COMBAT_PARALYSIS = 'quality:combat_paralyisis',
  DEPENDENTS = 'quality:dependents',
  DISTINCTIVE_STYLE = 'quality:distinctive_style',
  ELF_POSER = 'quality:elf_poser',
  GREMLINS = 'quality:gremlins',
  INCOMPETENT = 'quality:incompetent',
  INSOMNIA = 'quality:insomnia',
  LOSS_OF_CONFIDENCE = 'quality:loss_of_confidence',
  LOW_PAIN_TOLERANCE = 'quality:low_pain_tolerance',
  ORK_POSER = 'quality:ork_poser',
  PREJUDICED = 'quality:prejudiced',
  SCORCHED = 'quality:scorched',
  SENSITIVE_SYSTEM = 'quality:sensitive_system',
  SIMSENSE_VERTIGO = 'quality:simsense_vertigo',
  SINNER = 'quality:sinner',
  SOCIAL_STRESS = 'quality:social_stress',
  SPIRIT_BANE = 'quality:spirit_bane',
  UNCOUTH = 'quality:uncouth',
  UNEDUCATED = 'quality:uneducated',
  UNSTEADY_HANDS = 'quality:unsteady_hands',
  WEAK_IMMUNE_SYSTEM = 'quality:weak_immune_system'
}

export enum SKILL_ID {
  ARCHERY = 'skill:archery',
  AUTOMATICS = 'skill:automatics',
  BLADES = 'skill:blades',
  CLUBS = 'skill:clubs',
  EXOTIC_RANGED_WEAPON = 'skill:exotic_ranged_weapon',
  HEAVY_WEAPONS = 'skill:heavy_weapons',
  LONGARMS = 'skill:longarms',
  PISTOLS = 'skill:pistols',
  THROWING_WEAPONS = 'skill:throwing_weapons',
  UNARMED_COMBAT = 'skill:unarmed_combat',
  DISGUISE = 'skill:disguise',
  DIVING = 'skill:diving',
  ESCAPE_ARTIST = 'skill:escape_artist',
  FREE_FALL = 'skill:free-fall',
  GYMNASTICS = 'skill:gymnastics',
  PALMING = 'skill:palming',
  PERCEPTION = 'skill:perception',
  RUNNING = 'skill:running',
  SNEAKING = 'skill:sneaking',
  SURVIVAL = 'skill:survival',
  SWIMMING = 'skill:swimming',
  TRACKING = 'skill:tracking',
  CON = 'skill:con',
  ETIQUETTE = 'skill:etiquette',
  IMPERSONATION = 'skill:impersonation',
  INSTRUCTION = 'skill:instruction',
  INTIMIDATION = 'skill:intimidation',
  LEADERSHIP = 'skill:leadership',
  NEGOTIATION = 'skill:negotiation',
  PERFORMANCE = 'skill:performance',
  ALCHEMY = 'skill:alchemy',
  ARCANA = 'skill:arcana',
  ARTIFICING = 'skill:artificing',
  ASSENSING = 'skill:assensing',
  ASTRAL_COMBAT = 'skill:astral_combat',
  BANISHING = 'skill:banishing',
  BINDING = 'skill:binding',
  COUNTERSPELLING = 'skill:counterspelling',
  DISENCHANTING = 'skill:disenchanting',
  RITUAL_SPELLCASTING = 'skill:ritual_spellcasting',
  SPELLCASTING = 'skill:spellcasting',
  SUMMONING = 'skill:summoning',
  COMPILING = 'skill:compiling',
  DECOMPILING = 'skill:decompiling',
  REGISTERING = 'skill:registering',
  AERONAUTICS_MECHANIC = 'skill:aeronautics_mechanic',
  ANIMAL_HANDLING = 'skill:animal_handling',
  ARMORER = 'skill:armorer',
  ARTISAN = 'skill:artisan',
  AUTOMOTIVE_MECHANIC = 'skill:automotive_mechanic',
  BIOTECHNOLOGY = 'skill:biotechnology',
  CHEMISTRY = 'skill:chemistry',
  COMPUTER = 'skill:computer',
  CYBERCOMBAT = 'skill:cybercombat',
  CYBERTECHNOLOGY = 'skill:cybertechnology',
  DEMOLITIONS = 'skill:demolitions',
  ELECTRONIC_WARFARE = 'skill:electronic_warfare',
  FIRST_AID = 'skill:first_aid',
  FORGERY = 'skill:forgery',
  HACKING = 'skill:hacking',
  HARDWARE = 'skill:hardware',
  INDUSTRIAL_MECHANIC = 'skill:industrial_mechanic',
  LOCKSMITH = 'skill:locksmith',
  MEDICINE = 'skill:medicine',
  NAUTICAL_MECHANIC = 'skill:nautical_mechanic',
  NAVIGATION = 'skill:navigation',
  SOFTWARE = 'skill:software',
  GUNNERY = 'skill:gunnery',
  PILOT_AEROSPACE = 'skill:pilot_aerospace',
  PILOT_AIRCRAFT = 'skill:pilot_aircraft',
  PILOT_WALKER = 'skill:pilot_walker',
  PILOT_EXOTIC_VEHICLE = 'skill:pilot_exotic_vehicle',
  PILOT_GROUND_CRAFT = 'skill:pilot_ground_craft',
  PILOT_WATERCRAFT = 'skill:pilot_watercraft'
}

export enum SKILL_CATEGORY_ID {
  ACADEMIC = 'academic',
  INTERESTS = 'interests',
  PROFESSIONAL = 'professional',
  STREET = 'street',
  LANGUAGE = 'language'
}

export enum SPELL_ID {
  ACID_STREAM = 1,
  TOXIC_WAVE,
  PUNCH,
  CLOUT,
  BLAST,
  DEATH_TOUCH,
  MANABOLT,
  MANABALL,
  FLAMETHROWER,
  FIREBALL,
  LIGHTNING_BOLT,
  BALL_LIGHTNING,
  SHATTER,
  POWERBOLT,
  POWERBALL,
  KNOCKOUT,
  STUNBOLT,
  STUNBALL,
  ANALYZE_DEVICE,
  ANALYZE_MAGIC,
  ANALYZE_TRUTH,
  CLAIRAUDIENCE,
  CLAIRVOYANCE,
  COMBAT_SENSE,
  DETECT_ENEMIES,
  DETECT_ENEMIES_EXTENDED,
  DETECT_INDIVIDUAL,
  DETECT_LIFE,
  DETECT_LIFE_EXTENDED,
  DETECT_LIFE_FORM,
  DETECT_LIFE_FORM_EXTENDED,
  DETECT_MAGIC,
  DETECT_MAGIC_EXTENDED,
  DETECT_OBJECT,
  MINDLINK,
  MIND_PROBE,
  ANTIDOTE,
  CURE_DISEASE,
  DECREASE_ATTRIBUTE,
  DETOX,
  HEAL,
  INCREASE_ATTRIBUTE,
  INCREASE_REFLEXES,
  OXYGENATE,
  PROPHYLAXIS,
  RESIST_PAIN,
  STABILIZE,
  AGONY,
  MASS_AGONY,
  BUGS,
  SWARM,
  CONFUSION,
  MASS_CONFUSION,
  CHAOS,
  CHAOTIC_WORLD,
  ENTERTAINMENT,
  TRID_ENTERTAINMENT,
  INVISIBILITY,
  IMPROVED_INVISIBILITY,
  MASK,
  PHYSICAL_MASK,
  PHANTASM,
  TRID_PHANTASM,
  HUSH,
  SILENCE,
  STEALTH,
  ANIMATE,
  MASS_ANIMATE,
  ARMOR,
  CONTROL_ACTIONS,
  MOB_CONTROL,
  CONTROL_THOUGHTS,
  MOB_MIND,
  FLING,
  ICE_SHEET,
  IGNITE,
  INFLUENCE,
  LEVITATE,
  LIGHT,
  MAGIC_FINGERS,
  MANA_BARRIER,
  PHYSICAL_BARRIER,
  POLTERGEIST,
  SHADOW
}

export enum SPELL_CATEGORY_ID {
  COMBAT = 1,
  DETECTION,
  HEALTH,
  ILLUSION,
  MANIPULATION
}

export enum SPELL_DAMAGE_ID {
  PHYSICAL = 1,
  STUN
}

export enum SPELL_DURATION_ID {
  INSTANTANEOUS = 1,
  SUSTAINED,
  PERMANENT
}

export enum SPELL_KIND_ID {
  SPELL = 1,
  RITUAL,
  PREPARATION,
  FETISH_SPELL,
  FETISH_RITUAL
}

export enum SPELL_RANGE_ID {
  TOUCH = 1,
  LINE_OF_SIGHT,
  LINE_OF_SIGHT_AREA
}

export enum SPELL_SUBCATEGORY_ID {
  DIRECT = 1,
  INDIRECT,
  ELEMENTAL,
  ACTIVE,
  PASSIVE,
  DIRECTIONAL,
  AREA,
  EXTENDED_AREA,
  PSYCHIC,
  ESSENCE,
  OBVIOUS,
  REALISTIC,
  SINGLE_SENSE,
  MULTI_SENSE,
  MENTAL,
  PHYSICAL,
  ENVIRONMENTAL,
  DAMAGING
}

export enum SPELL_TYPE_ID {
  PHYSICAL = 1,
  MANA
}
