import {
  BOOK_ID,
  SPELL_CATEGORY_ID,
  SPELL_DAMAGE_ID,
  SPELL_DURATION_ID, SPELL_ID,
  SPELL_KIND_ID,
  SPELL_RANGE_ID,
  SPELL_SUBCATEGORY_ID,
  SPELL_TYPE_ID
} from './5e.enums';
import { Spell } from './5e.models';

export const SPELL_DAMAGE = [
  { id: SPELL_DAMAGE_ID.PHYSICAL, name: 'Physical', alias: 'P' },
  { id: SPELL_DAMAGE_ID.STUN, name: 'Stun', alias: 'S' }
];

export const SPELL_DURATIONS = [
  { id: SPELL_DURATION_ID.INSTANTANEOUS, name: 'Instantaneous', alias: 'I' },
  { id: SPELL_DURATION_ID.SUSTAINED, name: 'Sustained', alias: 'S' },
  { id: SPELL_DURATION_ID.PERMANENT, name: 'Permanent', alias: 'P' },
];

export const SPELL_KINDS = [
  { id: SPELL_KIND_ID.SPELL, name: 'Spell' },
  { id: SPELL_KIND_ID.RITUAL, name: 'Ritual' },
  { id: SPELL_KIND_ID.PREPARATION, name: 'Preparation' },
  { id: SPELL_KIND_ID.FETISH_SPELL, name: 'Fetish Spell' },
  { id: SPELL_KIND_ID.FETISH_RITUAL, name: 'Fetish Ritual' }
];

export const SPELL_RANGES = [
  { id: SPELL_RANGE_ID.TOUCH, name: 'Touch', alias: 'T' },
  { id: SPELL_RANGE_ID.LINE_OF_SIGHT, name: 'Line of Sight', alias: 'LOS' },
  { id: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA, name: 'Line of Sight (Area)', alias: 'LOS(A)' }
];

export const SPELL_SUBCATEGORIES = [
  { id: SPELL_SUBCATEGORY_ID.DIRECT, name: 'Direct' },
  { id: SPELL_SUBCATEGORY_ID.INDIRECT, name: 'Indirect' },
  { id: SPELL_SUBCATEGORY_ID.ELEMENTAL, name: 'Elemental' },
  { id: SPELL_SUBCATEGORY_ID.ACTIVE, name: 'Active' },
  { id: SPELL_SUBCATEGORY_ID.PASSIVE, name: 'Passive' },
  { id: SPELL_SUBCATEGORY_ID.DIRECTIONAL, name: 'Directional' },
  { id: SPELL_SUBCATEGORY_ID.AREA, name: 'Area' },
  { id: SPELL_SUBCATEGORY_ID.EXTENDED_AREA, name: 'Extended Area' },
  { id: SPELL_SUBCATEGORY_ID.PSYCHIC, name: 'Psychic' },
  { id: SPELL_SUBCATEGORY_ID.ESSENCE, name: 'Essence' },
  { id: SPELL_SUBCATEGORY_ID.OBVIOUS, name: 'Obvious' },
  { id: SPELL_SUBCATEGORY_ID.REALISTIC, name: 'Realistic' },
  { id: SPELL_SUBCATEGORY_ID.SINGLE_SENSE, name: 'Single-Sense' },
  { id: SPELL_SUBCATEGORY_ID.MULTI_SENSE, name: 'Multi-Sense' },
  { id: SPELL_SUBCATEGORY_ID.MENTAL, name: 'Mental' },
  { id: SPELL_SUBCATEGORY_ID.PHYSICAL, name: 'Physical' },
  { id: SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, name: 'Environmental' },
];

export const SPELL_TYPES = [
  { id: SPELL_TYPE_ID.PHYSICAL, name: 'Physical', alias: 'P' },
  { id: SPELL_TYPE_ID.MANA, name: 'Mana', alias: 'M' }
];

export const SPELLS: Spell[] = [
  {
    id: SPELL_ID.ACID_STREAM,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Acid Stream',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.TOXIC_WAVE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Toxic Wave',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.PUNCH,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Punch',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    damage: SPELL_DAMAGE_ID.STUN,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -6,
    specialty: false
  },
  {
    id: SPELL_ID.CLOUT,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Clout',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.BLAST,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Blast',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.DEATH_TOUCH,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Death Touch',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -6,
    specialty: false
  },
  {
    id: SPELL_ID.MANABOLT,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Manabolt',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.MANABALL,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Manaball',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.FLAMETHROWER,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Flamethrower',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.FIREBALL,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Fireball',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.LIGHTNING_BOLT,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Lightning Bolt',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.BALL_LIGHTNING,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Ball Lightning',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.SHATTER,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Shatter',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -6,
    specialty: false
  },
  {
    id: SPELL_ID.POWERBOLT,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'PowerBolt',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.POWERBALL,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'PowerBall',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.KNOCKOUT,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Knockout',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    damage: SPELL_DAMAGE_ID.STUN,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -6,
    specialty: false
  },
  {
    id: SPELL_ID.STUNBOLT,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'StunBolt',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.STUN,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.STUNBALL,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'StunBall',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.STUN,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.ANALYZE_DEVICE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Analyze Device',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.ANALYZE_MAGIC,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Analyze Magic',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.ANALYZE_TRUTH,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Analyze Truth',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.CLAIRAUDIENCE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Clairaudience',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.PASSIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.CLAIRVOYANCE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Clairvoyance',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.PASSIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.COMBAT_SENSE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Combat Sense',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.PASSIVE, SPELL_SUBCATEGORY_ID.PSYCHIC],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_ENEMIES,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Detect Enemies',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_ENEMIES_EXTENDED,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Detect Enemies, Extended',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.EXTENDED_AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_INDIVIDUAL,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Detect Individual',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_LIFE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Detect Life',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_LIFE_EXTENDED,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Detect Life, Extended',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.EXTENDED_AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_LIFE_FORM,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Detect [Life Form]',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: true
  },
  {
    id: SPELL_ID.DETECT_LIFE_FORM_EXTENDED,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Detect [Life Form], Extended',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.EXTENDED_AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: true
  },
  {
    id: SPELL_ID.DETECT_MAGIC,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Detect Magic',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_MAGIC_EXTENDED,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Detect Magic, Extended',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.EXTENDED_AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_OBJECT,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Detect Object',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: true
  },
  {
    id: SPELL_ID.MINDLINK,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'MindLink',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.PSYCHIC],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.MIND_PROBE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Mind Probe',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.ANTIDOTE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Antidote',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.CURE_DISEASE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Cure Disease',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [SPELL_SUBCATEGORY_ID.ESSENCE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.DECREASE_ATTRIBUTE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Decrease [Attribute]',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [SPELL_SUBCATEGORY_ID.ESSENCE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: true
  },
  {
    id: SPELL_ID.DETOX,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Detox',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -6,
    specialty: false
  },
  {
    id: SPELL_ID.HEAL,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Heal',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [SPELL_SUBCATEGORY_ID.ESSENCE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.INCREASE_ATTRIBUTE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Increase [Attribute]',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [SPELL_SUBCATEGORY_ID.ESSENCE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: true
  },
  {
    id: SPELL_ID.INCREASE_REFLEXES,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Increase Reflexes',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [SPELL_SUBCATEGORY_ID.ESSENCE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.OXYGENATE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Oxygenate',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -5,
    specialty: false
  },
  {
    id: SPELL_ID.PROPHYLAXIS,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Prophylaxis',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.RESIST_PAIN,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Resist Pain',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.STABILIZE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Stabilize',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.AGONY,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Agony',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.MASS_AGONY,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Mass Agony',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.BUGS,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Bugs',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.SWARM,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Swarm',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.CONFUSION,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Confusion',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.MASS_CONFUSION,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Mass Confusion',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.CHAOS,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Chaos',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.CHAOTIC_WORLD,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Chaotic World',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.ENTERTAINMENT,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Entertainment',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.OBVIOUS, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.TRID_ENTERTAINMENT,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Trid Entertainment',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.OBVIOUS, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.INVISIBILITY,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Invisibility',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.IMPROVED_INVISIBILITY,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Improved Invisibility',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.MASK,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Mask',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.PHYSICAL_MASK,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Physical Mask',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.PHANTASM,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Phantasm',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.TRID_PHANTASM,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Trid Phantasm',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.HUSH,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Hush',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.SILENCE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Silence',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.STEALTH,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Stealth',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.ANIMATE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Animate',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.MASS_ANIMATE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Mass Animate',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 1,
    specialty: false
  },
  {
    id: SPELL_ID.ARMOR,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Armor',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.CONTROL_ACTIONS,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Control Actions',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.MENTAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.MOB_CONTROL,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Mob Control',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.MENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 1,
    specialty: false
  },
  {
    id: SPELL_ID.CONTROL_THOUGHTS,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Control Thoughts',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.MENTAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.MOB_MIND,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Mob Mind',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.MENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 1,
    specialty: false
  },
  {
    id: SPELL_ID.FLING,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Fling',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL, SPELL_SUBCATEGORY_ID.DAMAGING],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.ICE_SHEET,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Ice Sheet',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.IGNITE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Ignite',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.INFLUENCE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Influence',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.MENTAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.LEVITATE,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Levitate',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.LIGHT,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Light',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.MAGIC_FINGERS,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Magic Fingers',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.MANA_BARRIER,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Mana Barrier',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.PHYSICAL_BARRIER,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Physical Barrier',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.POLTERGEIST,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Poltergeist',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.SHADOW,
    book: BOOK_ID.CORE_RULEBOOK,
    name: 'Shadow',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
];
