import {
  BOOK_ID,
  SPELL_CATEGORY_ID,
  SPELL_DAMAGE_ID,
  SPELL_DURATION_ID, SPELL_ID,
  SPELL_KIND_ID,
  SPELL_RANGE_ID,
  SPELL_SUBCATEGORY_ID,
  SPELL_TYPE_ID
} from './5e.enums';
import {BookId, Spell, SpellId} from './5e.models';

export const SPELL_DAMAGE = [
  { id: SPELL_DAMAGE_ID.PHYSICAL, name: 'Physical', alias: 'P' },
  { id: SPELL_DAMAGE_ID.STUN, name: 'Stun', alias: 'S' }
];

export const SPELL_DURATIONS = [
  { id: SPELL_DURATION_ID.INSTANTANEOUS, name: 'Instantaneous', alias: 'I' },
  { id: SPELL_DURATION_ID.SUSTAINED, name: 'Sustained', alias: 'S' },
  { id: SPELL_DURATION_ID.PERMANENT, name: 'Permanent', alias: 'P' },
];

export const SPELL_KINDS = [
  { id: SPELL_KIND_ID.SPELL, name: 'Spell' },
  { id: SPELL_KIND_ID.RITUAL, name: 'Ritual' },
  { id: SPELL_KIND_ID.PREPARATION, name: 'Preparation' },
  { id: SPELL_KIND_ID.FETISH_SPELL, name: 'Fetish Spell' },
  { id: SPELL_KIND_ID.FETISH_RITUAL, name: 'Fetish Ritual' }
];

export const SPELL_RANGES = [
  { id: SPELL_RANGE_ID.TOUCH, name: 'Touch', alias: 'T' },
  { id: SPELL_RANGE_ID.LINE_OF_SIGHT, name: 'Line of Sight', alias: 'LOS' },
  { id: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA, name: 'Line of Sight (Area)', alias: 'LOS(A)' }
];

export const SPELL_SUBCATEGORIES = [
  { id: SPELL_SUBCATEGORY_ID.DIRECT, name: 'Direct' },
  { id: SPELL_SUBCATEGORY_ID.INDIRECT, name: 'Indirect' },
  { id: SPELL_SUBCATEGORY_ID.ELEMENTAL, name: 'Elemental' },
  { id: SPELL_SUBCATEGORY_ID.ACTIVE, name: 'Active' },
  { id: SPELL_SUBCATEGORY_ID.PASSIVE, name: 'Passive' },
  { id: SPELL_SUBCATEGORY_ID.DIRECTIONAL, name: 'Directional' },
  { id: SPELL_SUBCATEGORY_ID.AREA, name: 'Area' },
  { id: SPELL_SUBCATEGORY_ID.EXTENDED_AREA, name: 'Extended Area' },
  { id: SPELL_SUBCATEGORY_ID.PSYCHIC, name: 'Psychic' },
  { id: SPELL_SUBCATEGORY_ID.ESSENCE, name: 'Essence' },
  { id: SPELL_SUBCATEGORY_ID.OBVIOUS, name: 'Obvious' },
  { id: SPELL_SUBCATEGORY_ID.REALISTIC, name: 'Realistic' },
  { id: SPELL_SUBCATEGORY_ID.SINGLE_SENSE, name: 'Single-Sense' },
  { id: SPELL_SUBCATEGORY_ID.MULTI_SENSE, name: 'Multi-Sense' },
  { id: SPELL_SUBCATEGORY_ID.MENTAL, name: 'Mental' },
  { id: SPELL_SUBCATEGORY_ID.PHYSICAL, name: 'Physical' },
  { id: SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, name: 'Environmental' },
];

export const SPELL_TYPES = [
  { id: SPELL_TYPE_ID.PHYSICAL, name: 'Physical', alias: 'P' },
  { id: SPELL_TYPE_ID.MANA, name: 'Mana', alias: 'M' }
];

export const SPELLS: Spell[] = [
  {
    id: SPELL_ID.ACID_STREAM as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Acid Stream',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.TOXIC_WAVE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Toxic Wave',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.PUNCH as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Punch',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    damage: SPELL_DAMAGE_ID.STUN,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -6,
    specialty: false
  },
  {
    id: SPELL_ID.CLOUT as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Clout',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.BLAST as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Blast',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.DEATH_TOUCH as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Death Touch',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -6,
    specialty: false
  },
  {
    id: SPELL_ID.MANABOLT as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Manabolt',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.MANABALL as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Manaball',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.FLAMETHROWER as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Flamethrower',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.FIREBALL as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Fireball',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.LIGHTNING_BOLT as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Lightning Bolt',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.BALL_LIGHTNING as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Ball Lightning',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.INDIRECT, SPELL_SUBCATEGORY_ID.ELEMENTAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.SHATTER as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Shatter',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -6,
    specialty: false
  },
  {
    id: SPELL_ID.POWERBOLT as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'PowerBolt',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.POWERBALL as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'PowerBall',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.PHYSICAL,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.KNOCKOUT as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Knockout',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    damage: SPELL_DAMAGE_ID.STUN,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -6,
    specialty: false
  },
  {
    id: SPELL_ID.STUNBOLT as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'StunBolt',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    damage: SPELL_DAMAGE_ID.STUN,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.STUNBALL as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'StunBall',
    category: SPELL_CATEGORY_ID.COMBAT,
    subcategories: [SPELL_SUBCATEGORY_ID.DIRECT],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    damage: SPELL_DAMAGE_ID.STUN,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.ANALYZE_DEVICE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Analyze Device',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.ANALYZE_MAGIC as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Analyze Magic',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.ANALYZE_TRUTH as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Analyze Truth',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.CLAIRAUDIENCE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Clairaudience',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.PASSIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.CLAIRVOYANCE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Clairvoyance',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.PASSIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.COMBAT_SENSE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Combat Sense',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.PASSIVE, SPELL_SUBCATEGORY_ID.PSYCHIC],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_ENEMIES as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Detect Enemies',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_ENEMIES_EXTENDED as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Detect Enemies, Extended',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.EXTENDED_AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_INDIVIDUAL as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Detect Individual',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_LIFE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Detect Life',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_LIFE_EXTENDED as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Detect Life, Extended',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.EXTENDED_AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_LIFE_FORM as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Detect [Life Form]',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: true
  },
  {
    id: SPELL_ID.DETECT_LIFE_FORM_EXTENDED as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Detect [Life Form], Extended',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.EXTENDED_AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: true
  },
  {
    id: SPELL_ID.DETECT_MAGIC as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Detect Magic',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_MAGIC_EXTENDED as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Detect Magic, Extended',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.EXTENDED_AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.DETECT_OBJECT as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Detect Object',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: true
  },
  {
    id: SPELL_ID.MINDLINK as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'MindLink',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.PSYCHIC],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.MIND_PROBE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Mind Probe',
    category: SPELL_CATEGORY_ID.DETECTION,
    subcategories: [SPELL_SUBCATEGORY_ID.ACTIVE, SPELL_SUBCATEGORY_ID.DIRECTIONAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.ANTIDOTE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Antidote',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.CURE_DISEASE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Cure Disease',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [SPELL_SUBCATEGORY_ID.ESSENCE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.DECREASE_ATTRIBUTE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Decrease [Attribute]',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [SPELL_SUBCATEGORY_ID.ESSENCE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: true
  },
  {
    id: SPELL_ID.DETOX as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Detox',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -6,
    specialty: false
  },
  {
    id: SPELL_ID.HEAL as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Heal',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [SPELL_SUBCATEGORY_ID.ESSENCE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.INCREASE_ATTRIBUTE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Increase [Attribute]',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [SPELL_SUBCATEGORY_ID.ESSENCE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: true
  },
  {
    id: SPELL_ID.INCREASE_REFLEXES as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Increase Reflexes',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [SPELL_SUBCATEGORY_ID.ESSENCE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.OXYGENATE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Oxygenate',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -5,
    specialty: false
  },
  {
    id: SPELL_ID.PROPHYLAXIS as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Prophylaxis',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.RESIST_PAIN as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Resist Pain',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.STABILIZE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Stabilize',
    category: SPELL_CATEGORY_ID.HEALTH,
    subcategories: [],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.AGONY as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Agony',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.MASS_AGONY as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Mass Agony',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.BUGS as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Bugs',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.SWARM as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Swarm',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.CONFUSION as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Confusion',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.MASS_CONFUSION as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Mass Confusion',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.CHAOS as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Chaos',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.CHAOTIC_WORLD as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Chaotic World',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.ENTERTAINMENT as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Entertainment',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.OBVIOUS, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
  {
    id: SPELL_ID.TRID_ENTERTAINMENT as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Trid Entertainment',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.OBVIOUS, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.INVISIBILITY as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Invisibility',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.IMPROVED_INVISIBILITY as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Improved Invisibility',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.MASK as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Mask',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.PHYSICAL_MASK as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Physical Mask',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.TOUCH,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.PHANTASM as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Phantasm',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.TRID_PHANTASM as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Trid Phantasm',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.MULTI_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.HUSH as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Hush',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.SILENCE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Silence',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.STEALTH as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Stealth',
    category: SPELL_CATEGORY_ID.ILLUSION,
    subcategories: [SPELL_SUBCATEGORY_ID.REALISTIC, SPELL_SUBCATEGORY_ID.SINGLE_SENSE],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.ANIMATE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Animate',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.MASS_ANIMATE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Mass Animate',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 1,
    specialty: false
  },
  {
    id: SPELL_ID.ARMOR as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Armor',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.CONTROL_ACTIONS as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Control Actions',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.MENTAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.MOB_CONTROL as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Mob Control',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.MENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 1,
    specialty: false
  },
  {
    id: SPELL_ID.CONTROL_THOUGHTS as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Control Thoughts',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.MENTAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.MOB_MIND as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Mob Mind',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.MENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: 1,
    specialty: false
  },
  {
    id: SPELL_ID.FLING as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Fling',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL, SPELL_SUBCATEGORY_ID.DAMAGING],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.ICE_SHEET as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Ice Sheet',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.INSTANTANEOUS,
    drain: 0,
    specialty: false
  },
  {
    id: SPELL_ID.IGNITE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Ignite',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.INFLUENCE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Influence',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.MENTAL],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.PERMANENT,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.LEVITATE as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Levitate',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.LIGHT as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Light',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -4,
    specialty: false
  },
  {
    id: SPELL_ID.MAGIC_FINGERS as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Magic Fingers',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.PHYSICAL],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.MANA_BARRIER as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Mana Barrier',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.MANA,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.PHYSICAL_BARRIER as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Physical Barrier',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -1,
    specialty: false
  },
  {
    id: SPELL_ID.POLTERGEIST as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Poltergeist',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -2,
    specialty: false
  },
  {
    id: SPELL_ID.SHADOW as SpellId,
    book: BOOK_ID.CORE_RULEBOOK as BookId,
    name: 'Shadow',
    category: SPELL_CATEGORY_ID.MANIPULATION,
    subcategories: [SPELL_SUBCATEGORY_ID.ENVIRONMENTAL, SPELL_SUBCATEGORY_ID.AREA],
    type: SPELL_TYPE_ID.PHYSICAL,
    range: SPELL_RANGE_ID.LINE_OF_SIGHT_AREA,
    duration: SPELL_DURATION_ID.SUSTAINED,
    drain: -3,
    specialty: false
  },
];
