
export enum AttributeId {
  STRENGTH = 'strength',
  AGILITY = 'agility',
  WITS = 'wits',
  EMPATHY = 'empathy',
}

export enum SkillId {
  MIGHT = 'might',
  ENDURANCE = 'endurance',
  MELEE = 'melee',
  CRAFTING = 'crafting',
  STEALTH = 'stealth',
  MOVE = 'move',
  SLEIGHT_OF_HAND = 'sleight_of_hand',
  MARKSMANSHIP = 'marksmanship',
  SCOUTING = 'scouting',
  LORE = 'lore',
  SURVIVAL = 'survival',
  INSIGHT = 'insight',
  MANIPULATION = 'manipulation',
  HEALING = 'healing',
  PERFORMANCE = 'performance',
  ANIMAL_HANDLING = 'animal_handling',
}

export enum KinId {
  HUMAN = 'human',
  ELF = 'elf',
  HALF_ELF = 'half_elf',
  DWARF = 'dwarf',
  HALFLING = 'halfling',
  WOLFKIN = 'wolfkin',
  ORC = 'orc',
  GOBLIN = 'goblin',
}

export enum TalentId {
  ADAPTIVE = 'adaptive',
  INNER_PEACE = 'inner_peace',
  PSYCHIC_POWER = 'psychic_power',
  TRUE_GRIT = 'true_grit',
  Hard_to_Catch = 'Hard_to_Catch',
  Hunting_Instincts = 'Hunting_Instincts',
  Unbreakable = 'Unbreakable',
  Nocturnal = 'Nocturnal',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
  // ADAPTIVE = '',
}
