import {Archetype} from './models';
import {ArchetypeId, ProfessionId, TraitId} from './enums';

export const ARCHETYPES: Archetype[] = [
  {
    id: ArchetypeId.COMMONER,
    name: 'Commoner',
    labels: {
      description: 'Professions of this Archetype are typically run-of-the-mill people, taking on regular jobs. Their occupations may vary by culture, but they live by the philosophy that hard work will ensure a bountiful, healthy and productive life.',
      wares: 'Backpack, Bandages (3), Blackpowder w/ Bullets (18), Candles (9), Fowler musket, Knife, Laudanum, Set of inferior clothes, Smelling salt and Tincture',
    },
    traits: [
      TraitId.ITS_OWN_REWARD,
      TraitId.JACK_OF_ALL_TRADES,
      TraitId.KEEP_IT_SIMPLE,
      TraitId.LOW_PROFILE,
      TraitId.MAKESHIFT_TOOLS,
      TraitId.NOSE_TO_THE_GRINDSTONE,
      TraitId.SALT_OF_THE_EARTH,
      TraitId.SHOW_THE_HEELS,
      TraitId.SKELETON_KEY,
      TraitId.WORK_WORK_WORK
    ],
    professions: [
      ProfessionId.BREWER,
      ProfessionId.GUNSMITH,
      ProfessionId.HIRED_HAND,
      ProfessionId.MERCHANT,
      ProfessionId.MIDWIFE,
      ProfessionId.PUBLICAN,
      ProfessionId.PURVEYOR,
      ProfessionId.SERVANT,
      ProfessionId.SMITH,
      ProfessionId.TAILOR,
      ProfessionId.WEAVER,
      ProfessionId.WRIGHT,
    ],
    money: [0, 0, 22]
  },
  {
    id: ArchetypeId.FRONTIER,
    name: 'Frontier',
    labels: {
      description: 'Professions of this Archetype typically live on the fringes of urban society and in the frontier lands. They make trade off the bounty the land affords them, hiring themselves out as surveyors and protecting others.',
      wares: 'Bandages (3), Blackpowder w/Bullets (18), Camping kit, Hatchet, Hunting bag, Musketoon, Laudanum, Set of inferior clothes, Smelling salt and Tincture'
    },
    traits: [
      TraitId.A_TALL_TALE,
      TraitId.DIAMOND_IN_THE_ROUGH,
      TraitId.FORTUITOUS_OUTCOMES,
      TraitId.FRONTIER_WALKER,
      TraitId.GUT_FOUNDED,
      TraitId.HANDS_OF_A_HEALER,
      TraitId.HIT_THE_HAY,
      TraitId.SHADOWS_BEGONE,
      TraitId.SLEEP_TIGHT,
      TraitId.TO_THE_BITTER_END
    ],
    professions: [
      ProfessionId.ANIMAL_WHISPERER,
      ProfessionId.BOATSWAIN,
      ProfessionId.DISPATCH_RIDER,
      ProfessionId.FARMER,
      ProfessionId.GREENGROCER,
      ProfessionId.MARINER,
      ProfessionId.MENDICANT,
      ProfessionId.RAMBLER,
      ProfessionId.ROAD_AGENT,
      ProfessionId.SURVEYOR,
      ProfessionId.SURVIVALIST,
      ProfessionId.WHALER,
    ],
    money: [0, 0, 33]
  },
  {
    id: ArchetypeId.INTELLECTUAL,
    name: 'Intellectual',
    labels: {
      description: 'Professions of this Archetype are learned, lettered and understand the value of the written word. They are of higher means, malleable and socially mobile.',
      wares: 'Bandages (3), Blackpowder w/Bullets (18), Book (one topic), Flintlock pistol, Knife, Laudanum, Set of average clothes, Smelling salt, Tincture and Writing kit'
    },
    traits: [
      TraitId.BY_THE_BOOK,
      TraitId.CHAOS_IS_A_LADDER,
      TraitId.ENCYCLOPEDIC_MEMORY,
      TraitId.ENFANT_TERRIBLE,
      TraitId.FIT_AS_A_FIDDLE,
      TraitId.HOLD_ON_A_MOMENT,
      TraitId.KNOWLEDGE_IS_POWER,
      TraitId.LOGICIAN,
      TraitId.STIFF_UPPER_LIP,
      TraitId.TONGUE_LASHING,
    ],
    professions: [
      ProfessionId.ARCHITECT,
      ProfessionId.ARTIST,
      ProfessionId.BARBER,
      ProfessionId.BOOKKEEPER,
      ProfessionId.DILETTANTE,
      ProfessionId.DIPLOMAT,
      ProfessionId.ENGRAVER,
      ProfessionId.LAWYER,
      ProfessionId.PRINTER,
      ProfessionId.STATIONER,
      ProfessionId.TEACHER,
      ProfessionId.TRANSLATOR,
    ],
    money: [0, 33, 0],
  },
  {
    id: ArchetypeId.LAWBREAKER,
    name: 'Lawbreaker',
    labels: {
      description: 'Professions of this Archetype are typically oath breakers or on the run from something or someone. They deal in lies, steal from the unwary and rabble-rouse to earn their keep, and with nothing to lose, they have little to fear.',
      wares: 'Antidote, Bandages (3), Blackpowder w/Bullets (18), Knife, Laudanum, Set of dark clothes, Smelling salt, Tincture, Tobacco (3) and Turn- out pistol'
    },
    traits: [
      TraitId.BETTER_LUCKY_THAN_GOOD,
      TraitId.DEAD_TO_RIGHTS,
      TraitId.ENTREPRENEURIAL_SPIRIT,
      TraitId.FAKE_IT_TILL_I_MAKE_IT,
      TraitId.MOSTLY_HARMLESS,
      TraitId.TAKE_A_MULLIGAN,
      TraitId.TREACHERY,
      TraitId.RING_OF_TRUTH,
      TraitId.WINDFALL,
      TraitId.WHITE_FEATHERED,
    ],
    professions: [
      ProfessionId.COUNTERFEITER,
      ProfessionId.CROOK,
      ProfessionId.FIREBRAND,
      ProfessionId.FREEBOOTER,
      ProfessionId.GAMBLER,
      ProfessionId.INFORMANT,
      ProfessionId.MUTINEER,
      ProfessionId.PARTISAN,
      ProfessionId.RESURRECTIONIST,
      ProfessionId.TOUT,
      ProfessionId.TURNCOAT,
      ProfessionId.VAGRANT,
    ],
    money: [0, 0, 11],
  },
  {
    id: ArchetypeId.MAGE,
    name: 'Mage',
    labels: {
      description: 'Professions of this Archetype make use of strange healing arts, plumb the depths of the supernatural and study Spells.They come from all walks of life and have sacrificed some part of their humanity to further their aims.',
      wares: 'Bandages (3), Blackpowder w/Bullets (18), Book of Common Spells, Knife, Laudanum, Overcoat pistol, Set of average clothes, Smelling salt, Tincture and Writing kit'
    },
    traits: [
      TraitId.ABRACADABRA,
      TraitId.ABSOLUTION,
      TraitId.DEVIL_IN_THE_EYE,
      TraitId.HAND_OF_GOD,
      TraitId.NO_ILLUSIONS,
      TraitId.RITUALISTIC,
      TraitId.SECOND_SIGHT,
      TraitId.TWIST_OF_FATE,
      TraitId.WELL_GROUNDED,
      TraitId.WITCHES_MARK,
    ],
    professions: [
      ProfessionId.ALCHEMIST,
      ProfessionId.APOTHECARY,
      ProfessionId.ASPIRANT,
      ProfessionId.BRAUCHER,
      ProfessionId.DOWSER,
      ProfessionId.FOLK_HEALER,
      ProfessionId.FORTUNE_TELLER,
      ProfessionId.HERBALIST,
      ProfessionId.MENTALIST,
      ProfessionId.PRECEPTOR,
      ProfessionId.SIN_EATER,
      ProfessionId.SPIRITUALIST,
    ],
    money: [11, 0, 0],
  },
  {
    id: ArchetypeId.URBANE,
    name: 'Urbane',
    labels: {
      description: 'Professions of this Archetype are typically knitted into social circles and ingratiate themselves to others with their skills in bending people to their whim. They are able to weaponize words and art for good and as cruel barbs when necessary.',
      wares: 'Bandages (3), Blackpowder w/Bullets (18), Flintlock pistol, Knife, Laudanum, Ledger, Set of superior clothes, Smelling salt, Tincture and Writing kit'
    },
    traits: [
      TraitId.BETWEEN_TWO_WORLDS,
      TraitId.DYED_IN_THE_WOOL,
      TraitId.E_PLURIBUS_UNUM,
      TraitId.FOSTERING_COMMUNITY,
      TraitId.LEVEL_HEADED,
      TraitId.PEOPLE_PERSON,
      TraitId.SELF_RELIANT,
      TraitId.SEVENTH_SENSE,
      TraitId.TITAN_OF_INDUSTRY,
      TraitId.VOX_POPULI,
    ],
    professions: [
      ProfessionId.ACTOR,
      ProfessionId.BAWD,
      ProfessionId.CLERGY,
      ProfessionId.CLERK,
      ProfessionId.LIBERTINE,
      ProfessionId.MAGISTRATE,
      ProfessionId.MILLINER,
      ProfessionId.MUSICIAN,
      ProfessionId.POLITICIAN,
      ProfessionId.TAX_COLLECTOR,
      ProfessionId.TOWN_CRIER,
      ProfessionId.WRITER,
    ],
    money: [22, 0, 0],
  },
  {
    id: ArchetypeId.WARRIOR,
    name: 'Warrior',
    labels: {
      description: 'Professions of this Archetype are typically fighters of a type, but not necessarily trained in the ways of the military. Most are not long for this world, as the trades they ply deal strictly in violence as a means to an end.',
      wares: 'Bandages (3), Bayonet, Bedroll, Blackpowder w/Bullets (18), Brown Bess musket, Knapsack, Laudanum, Set of inferior clothes, Smelling salt and Tincture'
    },
    traits: [
      TraitId.ARMED_TO_THE_TEETH,
      TraitId.BATTLE_HYMN,
      TraitId.BITE_THE_BULLET,
      TraitId.BLOODY_MINDED,
      TraitId.FEATHER_IN_THE_CAP,
      TraitId.LIBERTY_OR_DEATH,
      TraitId.LOCK_STOCK_AND_BARREL,
      TraitId.MAKE_A_BEELINE,
      TraitId.SET_MY_SIGHTS,
      TraitId.TURN_THE_TABLES,
    ],
    professions: [
      ProfessionId.AUXILIARY,
      ProfessionId.CAVALRY,
      ProfessionId.DESERTER,
      ProfessionId.FUR_TRAPPER,
      ProfessionId.GRENADIER,
      ProfessionId.GUERILLA,
      ProfessionId.LAMPLIGHTER,
      ProfessionId.MILITIA,
      ProfessionId.OFFICER,
      ProfessionId.PRIVATEER,
      ProfessionId.REGULAR,
      ProfessionId.TRACKER,
    ],
    money: [0, 0, 22],
  }
];
