import {LanguageId} from './enums';
import {Language} from './models';

export const LANGUAGES: Language[] = [
  { id: LanguageId.ABENAKI, name: 'Abenaki' },
  { id: LanguageId.ALGONQUIN, name: 'Algonquin' },
  { id: LanguageId.APALACHEE, name: 'Apalachee' },
  { id: LanguageId.ATIKAMEKW, name: 'Atikamekw' },
  { id: LanguageId.CATAWBA, name: 'Catawba' },
  { id: LanguageId.CHICKASAW, name: 'Chickasaw' },
  { id: LanguageId.CREOLE, name: 'Creole' },
  { id: LanguageId.DUTCH, name: 'Dutch' },
  { id: LanguageId.ENGLISH, name: 'English' },
  { id: LanguageId.FRENCH, name: 'French' },
  { id: LanguageId.GERMAN, name: 'German' },
  { id: LanguageId.GREEK, name: 'Greek' },
  { id: LanguageId.HAUDENOSAUNEE, name: 'Haudenosaunee' },
  { id: LanguageId.HEBREW, name: 'Hebrew' },
  { id: LanguageId.INNU, name: 'Innu' },
  { id: LanguageId.LATIN, name: 'Latin' },
  { id: LanguageId.LENAPE, name: 'Lenape' },
  { id: LanguageId.LINGUA_FRANCA, name: 'Lingua Franca' },
  { id: LanguageId.MAHICAN, name: 'Mahican' },
  { id: LanguageId.MASSACHUSETT, name: 'Massachusett' },
  { id: LanguageId.PIDGIN, name: 'Pidgin' },
  { id: LanguageId.PORTUGUESE, name: 'Portuguese' },
  { id: LanguageId.POWHATAN, name: 'Powhatan' },
  { id: LanguageId.RUSSIAN, name: 'Russian' },
  { id: LanguageId.SEMINOLE, name: 'Seminole' },
  { id: LanguageId.SHAWNEE, name: 'Shawnee' },
  { id: LanguageId.SPANISH, name: 'Spanish' },
  { id: LanguageId.SWEDISH, name: 'Swedish' },
  { id: LanguageId.TSALAGI, name: 'Tsalagi' },
  { id: LanguageId.WAMPANOAG, name: 'Wampanoag' },
  //
  // { id: LanguageId.GUARANI, name: 'Guaraní' },
  // { id: LanguageId.CHEROKEE, name: 'Cherokee' },
  // { id: LanguageId.CHIPEWYAN, name: 'Chipewyan' },
  // { id: LanguageId.ESKIMO_ALEUT, name: 'Eskimo-Aleut' },
  // { id: LanguageId.CHIPEWYAN, name: 'Chipewyan' },
];
